// safeFormatToUuid.ts
// Converts any user identifier to a valid UUID so it can be stored in Postgres.
//
// THE PROBLEM: Clerk user IDs look like "user_2NNPxxxxxxxxx" — a plain string,
// not a UUID. Postgres UUID columns reject these with a type error.
//
// THE SOLUTION: UUID v5 (name-based hashing using SHA-1). Given the same input
// string and namespace, it always produces the same UUID output. That means a
// user's Clerk ID will always map to the same DB UUID — so their history stays
// connected across sessions.
//
// Anonymous device IDs are already random UUIDs (generated by
// window.crypto.randomUUID() in useDeviceId.ts), so those pass through unchanged.

import { v5, validate } from "uuid";
import dotenv from "dotenv";
dotenv.config(); // no-op in Next.js; needed only when run directly as a CLI script

// Fallback is the "DNS namespace" UUID defined in RFC 4122 § 4.3.
// Any stable string works as a namespace — this built-in value is just a safe
// default for when the CLERK_UUID_NAMESPACE environment variable is absent.
const CLERK_UUID_NAMESPACE =
  process.env.CLERK_UUID_NAMESPACE || "6ba7b810-9dad-11d1-80b4-00c04fd430c8";

// validate(id) returns true if id is already a properly formatted UUID (e.g.
// the anonymous device UUID from localStorage). Those pass through untouched.
// Non-UUID strings (Clerk IDs) are hashed into a deterministic UUID via v5.
const safeFormatToUuid = (id: string): string => {
  if (validate(id)) {
    return id; // already a valid UUID — no conversion needed
  }
  // v5(name, namespace) → deterministic UUID derived from SHA-1 hash.
  // The same Clerk ID + same namespace always produces the same UUID.
  return v5(id, CLERK_UUID_NAMESPACE);
};

export { safeFormatToUuid };
